<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateProovedoresTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('proovedores', function (Blueprint $table) {
            $table->id();
            $table->integer('legajo')->unique(); // Unique provider number
            $table->string('nombre'); // Provider's name
            $table->bigInteger('numeroDeTelefono')->nullable(); // Phone number as long int, nullable
            $table->string('tipo')->nullable(); // Type of provider
            $table->timestamps(); // Created_at and updated_at timestamps
        });

        DB::table('proovedores')->insert([
            ['legajo' => 1, 'nombre' => 'Ebuy - Place'],
            ['legajo' => 2, 'nombre' => 'Maderera Misiones'],
            ['legajo' => 3, 'nombre' => 'RAM OLAVARRIA'],
            ['legajo' => 4, 'nombre' => 'Olavarría Goma'],
            ['legajo' => 5, 'nombre' => 'Ferreteria EL URUGUAYO'],
            ['legajo' => 6, 'nombre' => 'Zito Y Priola'],
            ['legajo' => 7, 'nombre' => 'Alquilo Todo'],
            ['legajo' => 8, 'nombre' => 'Santiago Masson S.A.'],
            ['legajo' => 9, 'nombre' => 'Casa Bouciguez S.A.'],
            ['legajo' => 10, 'nombre' => 'Singla Electricidad S.A.A'],
            ['legajo' => 11, 'nombre' => 'Dos Santos Christian Raul'],
            ['legajo' => 12, 'nombre' => 'El Corralón'],
            ['legajo' => 13, 'nombre' => 'Repuestos Agricolas Colon'],
            ['legajo' => 14, 'nombre' => 'Ruppel Javier Edgardo'],
            ['legajo' => 15, 'nombre' => 'Materiales Pellegrini'],
            ['legajo' => 16, 'nombre' => 'Carrefour'],
            ['legajo' => 17, 'nombre' => 'Hierros Gonzalez'],
            ['legajo' => 18, 'nombre' => 'Estación de Servicio AXION ENERGY'],
            ['legajo' => 19, 'nombre' => 'Arrospide Materiales'],
            ['legajo' => 20, 'nombre' => 'Ebuy - Place'],
            ['legajo' => 21, 'nombre' => 'Hernando Hnos S.A.'],
            ['legajo' => 22, 'nombre' => 'Raiz Comercial'],
            ['legajo' => 23, 'nombre' => 'Repuestos "Chiappe"'],
            ['legajo' => 24, 'nombre' => 'Izaguirre Amoroso S.A.'],
            ['legajo' => 25, 'nombre' => 'Soluciones en Herramientas C.T.L'],
            ['legajo' => 26, 'nombre' => 'Sierra Marina Alejandra Beatriz'],
            ['legajo' => 27, 'nombre' => 'Estacion de servicio DAPSA'],
            ['legajo' => 28, 'nombre' => 'Ferreteria El Pato'],
            ['legajo' => 29, 'nombre' => 'Lubrigom'],
            ['legajo' => 30, 'nombre' => 'Gobel Nicolas'],
            ['legajo' => 31, 'nombre' => 'Materiales Silva'],
            ['legajo' => 32, 'nombre' => 'Tapia Sergio Daniel'],
            ['legajo' => 33, 'nombre' => 'Materiales Rurales El Quebracho'],
            ['legajo' => 34, 'nombre' => 'Corralon Materiales ESTO'],
            ['legajo' => 35, 'nombre' => 'Materiales El Hangar SA'],
            ['legajo' => 36, 'nombre' => 'Soraiz Ramos Generales'],
            ['legajo' => 37, 'nombre' => 'Valparaiso S.A.'],
            ['legajo' => 38, 'nombre' => 'Comasa S.A.'],
            ['legajo' => 39, 'nombre' => 'Repuestos Romero'],
            ['legajo' => 40, 'nombre' => 'Pintureria del Centro'],
            ['legajo' => 41, 'nombre' => 'Axion Energy Estacion de servicio'],
            ['legajo' => 42, 'nombre' => 'Telefonica Argentina S.A.'],
            ['legajo' => 43, 'nombre' => 'Repuestos Chiape'],
            ['legajo' => 44, 'nombre' => 'El Manu'],
            ['legajo' => 45, 'nombre' => 'Todo Ruleman'],
            ['legajo' => 46, 'nombre' => 'Pica Juan Jose'],
            ['legajo' => 47, 'nombre' => 'Fase 3'],
            ['legajo' => 48, 'nombre' => 'La casa de los cristales'],
            ['legajo' => 49, 'nombre' => 'La comarca aberturas'],
            ['legajo' => 50, 'nombre' => 'Impermeabilizaciones Federico'],
            ['legajo' => 51, 'nombre' => 'Gas Carielli'],
            ['legajo' => 52, 'nombre' => 'FyG '],
            ['legajo' => 53, 'nombre' => 'Premet'],
            ['legajo' => 54, 'nombre' => 'C&R de Olavarria'],
            ['legajo' => 55, 'nombre' => 'Tecnofrio'],
            ['legajo' => 56, 'nombre' => 'Pintureria El Planeta'],
            ['legajo' => 57, 'nombre' => 'Librería Altamira'],
            ['legajo' => 58, 'nombre' => 'Appul Iteuve Argentina S.A.'],
            ['legajo' => 59, 'nombre' => 'Andrich e Hijos'],
            ['legajo' => 60, 'nombre' => 'Servicentro colon'],
            ['legajo' => 61, 'nombre' => 'Olafil'],
            ['legajo' => 62, 'nombre' => 'Yicar'],
            ['legajo' => 63, 'nombre' => 'EESS S.A:'],
            ['legajo' => 64, 'nombre' => 'Movistar'],
            ['legajo' => 65, 'nombre' => 'FER-SAN Ferreteria'],
            ['legajo' => 66, 'nombre' => 'Tancredi'],
            ['legajo' => 67, 'nombre' => 'Logistica Olavarria'],
            ['legajo' => 68, 'nombre' => 'Ferreteria Avenida'],
            ['legajo' => 69, 'nombre' => 'Sanitola S.A.'],
            ['legajo' => 70, 'nombre' => 'Distribuidora Chantiri'],
            ['legajo' => 71, 'nombre' => 'Ferreteria Galarza S.A.'],
            ['legajo' => 72, 'nombre' => 'FiPHSA'],
            ['legajo' => 73, 'nombre' => 'El Emporio del Soldador'],
            ['legajo' => 74, 'nombre' => 'Ferreteria de Colores'],
            ['legajo' => 75, 'nombre' => 'Expreso Velomax'],
            ['legajo' => 76, 'nombre' => 'Clementi'],
            ['legajo' => 77, 'nombre' => 'Vialmet SRL'],
            ['legajo' => 78, 'nombre' => 'TOP SA'],
            ['legajo' => 79, 'nombre' => 'Diaz Natali'],
            ['legajo' => 80, 'nombre' => 'Gori Luciano'],
            ['legajo' => 81, 'nombre' => 'Neumacentro S.A.'],
            ['legajo' => 82, 'nombre' => 'Curra '],
            ['legajo' => 83, 'nombre' => 'Bringeri'],
            ['legajo' => 84, 'nombre' => 'MORC SRL'],
            ['legajo' => 85, 'nombre' => 'Olanet'],
            ['legajo' => 86, 'nombre' => 'Capitanich Construcciones S.A.'],
            ['legajo' => 87, 'nombre' => 'Barrera Gerardo Julian'],
            ['legajo' => 88, 'nombre' => 'ALL.Com'],
            ['legajo' => 89, 'nombre' => 'Pintureria Arco iris'],
            ['legajo' => 90, 'nombre' => 'Terar S.A.'],
            ['legajo' => 91, 'nombre' => 'Su Seguridad'],
            ['legajo' => 92, 'nombre' => 'Iuterig Ana Catalina'],
            ['legajo' => 93, 'nombre' => 'Tubos Olavarria'],
            ['legajo' => 94, 'nombre' => 'Augusto Hiese'],
            ['legajo' => 95, 'nombre' => 'Collins Industrial SRL'],
            ['legajo' => 96, 'nombre' => 'GeoBauen'],
            ['legajo' => 97, 'nombre' => 'Deterxil'],
            ['legajo' => 98, 'nombre' => 'Rulemanes BIAR'],
            ['legajo' => 99, 'nombre' => 'Union Indutrial de Olavarria'],
            ['legajo' => 100, 'nombre' => 'Aladino librería'],
            ['legajo' => 101, 'nombre' => 'Pronor SRL'],
            ['legajo' => 102, 'nombre' => 'Organización Manuel Oscar Lopez'],
            ['legajo' => 103, 'nombre' => 'Inferbul '],
            ['legajo' => 104, 'nombre' => 'IERIC'],
            ['legajo' => 105, 'nombre' => 'Plastigas S.A.'],
            ['legajo' => 106, 'nombre' => 'Martinez Escalada S.A.'],
            ['legajo' => 107, 'nombre' => 'Movistar PIO'],
            ['legajo' => 108, 'nombre' => 'Union Industrial de Olavarria'],
            ['legajo' => 109, 'nombre' => 'PIPHSA'],
            ['legajo' => 110, 'nombre' => 'SIMPI S.A.'],
            ['legajo' => 111, 'nombre' => 'Soraiz'],
            ['legajo' => 112, 'nombre' => 'Curra'],
            ['legajo' => 113, 'nombre' => 'Lubricentro Del Valle'],
            ['legajo' => 114, 'nombre' => 'Messineo maderas'],
            ['legajo' => 115, 'nombre' => 'Maximo GIFFONI S.A.'],
            ['legajo' => 116, 'nombre' => 'Diesel San Gabriel'],
            ['legajo' => 117, 'nombre' => 'Desarroladora IMZA S.A.'],
            ['legajo' => 118, 'nombre' => 'Papeleria Ciuffo'],
            ['legajo' => 119, 'nombre' => "Repuestod D'Onofrio"],
            ['legajo' => 120, 'nombre' => 'Stunek Mario Alberto'],
            ['legajo' => 121, 'nombre' => 'Toyomec '],
            ['legajo' => 122, 'nombre' => 'Corralon ESTO'],
            ['legajo' => 123, 'nombre' => 'El Hangar'],
            ['legajo' => 124, 'nombre' => 'Casa Singla'],
            ['legajo' => 125, 'nombre' => 'Administracion PIO 1'],
            ['legajo' => 126, 'nombre' => 'Asociacion PIO 1'],
            ['legajo' => 127, 'nombre' => 'Hoffmann Ezequiel Arsenio'],
            ['legajo' => 128, 'nombre' => 'OESER  S.A.'],
            ['legajo' => 129, 'nombre' => 'Abrigo Hernando SRL'],
            ['legajo' => 130, 'nombre' => 'Luis Roma'],
            ['legajo' => 131, 'nombre' => 'Estacion servicio Pascua'],
            ['legajo' => 132, 'nombre' => 'Digital Curra'],
            ['legajo' => 133, 'nombre' => 'Materiales Avenida VAF'],
            ['legajo' => 134, 'nombre' => 'Area 226'],
            ['legajo' => 135, 'nombre' => 'Cortinas Quili-Cort'],
            ['legajo' => 136, 'nombre' => 'Rekofsky Barragan Marisol'],
            ['legajo' => 137, 'nombre' => 'Bazar Centenari'],
            ['legajo' => 138, 'nombre' => 'Concientizar Servicios Seg e Hig'],
            ['legajo' => 139, 'nombre' => 'Applus Iteuve  Argentina S.A.'],
            ['legajo' => 140, 'nombre' => 'La Casa de los Hierros S.A.'],
            ['legajo' => 141, 'nombre' => 'Mapis Carlos Antonio'],
            ['legajo' => 142, 'nombre' => 'Induca S.C'],
            ['legajo' => 143, 'nombre' => 'Correo Argentino'],
            ['legajo' => 144, 'nombre' => 'Ramos Generales Soraiz'],
            ['legajo' => 145, 'nombre' => 'Chiape Domina'],
            ['legajo' => 146, 'nombre' => 'Estacion servicio Marino'],
            ['legajo' => 147, 'nombre' => 'Uria Repuestos'],
            ['legajo' => 148, 'nombre' => 'Occhi Sergio Daniel'],
            ['legajo' => 149, 'nombre' => 'Curra Digitals'],
            ['legajo' => 150, 'nombre' => 'Parlante Jose Eustaquio'],
            ['legajo' => 151, 'nombre' => 'Santarios 9 de julio'],
            ['legajo' => 152, 'nombre' => 'Librería Ciuffo'],
            ['legajo' => 153, 'nombre' => 'Combu SRL'],
            ['legajo' => 154, 'nombre' => 'Grandi Jose Luis'],
            ['legajo' => 155, 'nombre' => 'Seguridad Morc'],
            ['legajo' => 156, 'nombre' => 'Bellagamba Marcos Alberto'],
            ['legajo' => 157, 'nombre' => 'Ingenieria Integral SRL'],
            ['legajo' => 158, 'nombre' => 'Betonmac SA'],
            ['legajo' => 159, 'nombre' => 'Hernando Hnos'],
            ['legajo' => 160, 'nombre' => 'Plastigas SA'],
            ['legajo' => 161, 'nombre' => 'CAB Accesorios srl'],
            ['legajo' => 162, 'nombre' => 'Pecma srl'],
            ['legajo' => 163, 'nombre' => 'De Gisi Antonio Luis'],
            ['legajo' => 164, 'nombre' => 'Via Cargo'],
            ['legajo' => 165, 'nombre' => 'Opessa Aca Olavarria'],
            ['legajo' => 166, 'nombre' => 'Bulones Randazzo'],
            ['legajo' => 167, 'nombre' => 'Sew Combustibles'],
            ['legajo' => 168, 'nombre' => 'Hotel León'],
            ['legajo' => 169, 'nombre' => 'Adalberto Jorge Leal'],
            ['legajo' => 170, 'nombre' => 'Olavarria Goma'],
            ['legajo' => 171, 'nombre' => 'Estacion Servicio Hernando Hnos'],
            ['legajo' => 172, 'nombre' => 'Pedro Camino SRL'],
            ['legajo' => 173, 'nombre' => 'Schwindt Jose Dario'],
            ['legajo' => 174, 'nombre' => 'Estacion servicio De Martino'],
            ['legajo' => 175, 'nombre' => 'Cientifica Integral Palermo'],
            ['legajo' => 176, 'nombre' => 'Estacion sericio De Martino'],
            ['legajo' => 177, 'nombre' => 'Induca S.C.'],
            ['legajo' => 178, 'nombre' => 'Sistemas y servicios S.A.'],
            ['legajo' => 179, 'nombre' => 'Grand Prix'],
            ['legajo' => 180, 'nombre' => 'Inferbul'],
            ['legajo' => 181, 'nombre' => 'Petrotandil S.A.'],
            ['legajo' => 182, 'nombre' => 'Oviedo Paloma'],
            ['legajo' => 183, 'nombre' => 'Estacion servico Dapsa'],
            ['legajo' => 184, 'nombre' => 'Fioroni Maria Cecilia'],
            ['legajo' => 185, 'nombre' => 'Sergio Occhi'],
            ['legajo' => 186, 'nombre' => 'TOP S.A.'],
            ['legajo' => 187, 'nombre' => 'Frenos Corradi'],
            ['legajo' => 188, 'nombre' => 'Electricidad Olavarria'],
            ['legajo' => 189, 'nombre' => 'PPC'],
            ['legajo' => 190, 'nombre' => 'Petro Argentina'],
            ['legajo' => 191, 'nombre' => 'Opessa Las Flores'],
            ['legajo' => 192, 'nombre' => 'Fasciolo Juliana'],
            ['legajo' => 193, 'nombre' => 'Perello Maria Giselle'],
            ['legajo' => 194, 'nombre' => 'Todo Ruleman '],
            ['legajo' => 195, 'nombre' => 'Ardino Vidrios y Aberturas'],
            ['legajo' => 196, 'nombre' => 'ByC Ferreteria'],
            ['legajo' => 197, 'nombre' => 'RAM'],
            ['legajo' => 198, 'nombre' => 'Materiale Alsina'],
            ['legajo' => 199, 'nombre' => 'Sarraille Hnos SRL'],
            ['legajo' => 200, 'nombre' => 'IMACO'],
            ['legajo' => 201, 'nombre' => 'Desarrolladora IMZA'],
            ['legajo' => 202, 'nombre' => 'Simpi '],
            ['legajo' => 203, 'nombre' => 'Hoffman Ezequiel'],
            ['legajo' => 204, 'nombre' => 'Gonzalez Carlos Manuel'],
            ['legajo' => 205, 'nombre' => 'Repuestos Donofrio'],
            ['legajo' => 206, 'nombre' => 'Ferreteria ByC'],
            ['legajo' => 207, 'nombre' => 'Estacion servicio Dapsa'],
            ['legajo' => 208, 'nombre' => 'Comasa'],
            ['legajo' => 209, 'nombre' => 'Gas Carelli'],
            ['legajo' => 210, 'nombre' => 'Catriel Mapu S.A.'],
            ['legajo' => 211, 'nombre' => 'Estacion De Martino'],
            ['legajo' => 212, 'nombre' => 'Castagnari'],
            ['legajo' => 213, 'nombre' => 'Pintureria Avenida'],
            ['legajo' => 214, 'nombre' => 'Tuccio Ricardo Dante'],
            ['legajo' => 215, 'nombre' => 'Morc Seguridad'],
            ['legajo' => 216, 'nombre' => 'CLACE Revestimiento'],
            ['legajo' => 217, 'nombre' => 'Ferreteria Lubirgom'],
            ['legajo' => 218, 'nombre' => 'ORVE OLAVARRIA SRL'],
            ['legajo' => 219, 'nombre' => 'ARBA'],
            ['legajo' => 220, 'nombre' => 'Hiercons SRL'],
            ['legajo' => 221, 'nombre' => 'Samatan Federico'],
            ['legajo' => 222, 'nombre' => 'Vega Carlos Alberto'],
            ['legajo' => 223, 'nombre' => 'Hormigones Cardales S.A.'],
            ['legajo' => 224, 'nombre' => 'Iriarte Ingenieria SRL'],
            ['legajo' => 225, 'nombre' => 'Ricardo Tuccio'],
            ['legajo' => 226, 'nombre' => 'Repuestos ZAM'],
            ['legajo' => 227, 'nombre' => 'La Tri-via SRL'],
            ['legajo' => 228, 'nombre' => 'Opessa San Martin de Loa Andes'],
            ['legajo' => 229, 'nombre' => 'Axion Piedra del Aguila'],
            ['legajo' => 230, 'nombre' => 'Estacion servicio YPF'],
            ['legajo' => 231, 'nombre' => 'Rio salado SRL'],
            ['legajo' => 232, 'nombre' => 'Librería y papeleria Ciufo'],
            ['legajo' => 233, 'nombre' => 'Sanitarios Tancredi'],
            ['legajo' => 234, 'nombre' => 'Campomenosi Matias'],
            ['legajo' => 235, 'nombre' => 'Materiles ALBIN'],
            ['legajo' => 236, 'nombre' => 'Olavarria Electricidad'],
            ['legajo' => 237, 'nombre' => 'Barros Aldana Magali'],
            ['legajo' => 238, 'nombre' => 'Masson Abril Rocio'],
            ['legajo' => 239, 'nombre' => 'Farra Rocio Belen'],
            ['legajo' => 240, 'nombre' => 'Parabrisas Lastra'],
            ['legajo' => 241, 'nombre' => 'SARAYA Equpamientos'],
            ['legajo' => 242, 'nombre' => 'El manu materiales rurales'],
            ['legajo' => 243, 'nombre' => 'Chilli Parts'],
            ['legajo' => 244, 'nombre' => 'Chaparraro Jacinto Alberto'],
            ['legajo' => 245, 'nombre' => 'Ministerio Trabajo'],
            ['legajo' => 246, 'nombre' => 'Servisteel Mar del Plata'],
            ['legajo' => 247, 'nombre' => 'Martha Loustau S.A.'],
            ['legajo' => 248, 'nombre' => 'Taday Patricia Elena'],
            ['legajo' => 249, 'nombre' => 'Repuestos Dentaro'],
            ['legajo' => 250, 'nombre' => 'Gottfrit y Vazzzano SH'],
            ['legajo' => 251, 'nombre' => 'Olafil '],
            ['legajo' => 252, 'nombre' => 'ZAM autopartes'],
            ['legajo' => 253, 'nombre' => 'Modarelli Carlos Alberto'],
            ['legajo' => 254, 'nombre' => 'Diesel Rebolo S.A.'],
            ['legajo' => 255, 'nombre' => 'Electromecanica Planes'],
            ['legajo' => 256, 'nombre' => 'Olanet SRl'],
            ['legajo' => 257, 'nombre' => 'STI Digital'],
            ['legajo' => 258, 'nombre' => 'Barone Fabian'],
            ['legajo' => 259, 'nombre' => 'Ferreteria Victor'],
            ['legajo' => 260, 'nombre' => 'Estacion VOY'],
            ['legajo' => 261, 'nombre' => 'Area 226 Energia SA'],
            ['legajo' => 262, 'nombre' => 'Materiales Pelegrini'],
            ['legajo' => 263, 'nombre' => 'Alacantarillas VRCESA'],
            ['legajo' => 264, 'nombre' => 'Materiales Arrospide'],
            ['legajo' => 265, 'nombre' => 'Ferreteria Galarza'],
            ['legajo' => 266, 'nombre' => 'Abalona'],
            ['legajo' => 267, 'nombre' => 'Ambito'],
            ['legajo' => 268, 'nombre' => 'Materiales Bouciguez'],
            ['legajo' => 269, 'nombre' => 'Phicol'],
            ['legajo' => 270, 'nombre' => 'Materiales Construccion IMACO'],
            ['legajo' => 271, 'nombre' => 'Papelera Ciuffo'],
            ['legajo' => 272, 'nombre' => 'Sunder Ventas'],
            ['legajo' => 273, 'nombre' => 'Covacon SRL'],
            ['legajo' => 274, 'nombre' => 'SIM - MANGANO'],
            ['legajo' => 275, 'nombre' => 'Anselmo Matias Ezequiel'],
            ['legajo' => 276, 'nombre' => 'Orrade Pablo Jose'],
            ['legajo' => 277, 'nombre' => 'Finoteix'],
            ['legajo' => 278, 'nombre' => 'Sigma Tec.'],
            ['legajo' => 279, 'nombre' => 'Globalmart'],
            ['legajo' => 280, 'nombre' => 'Oppesa'],
            ['legajo' => 281, 'nombre' => 'Chiape'],
            ['legajo' => 282, 'nombre' => 'Ferreteria soraiz'],
            ['legajo' => 283, 'nombre' => 'Crucero expres'],
            ['legajo' => 284, 'nombre' => 'Pintar Olavarria S.A.'],
            ['legajo' => 285, 'nombre' => 'Ortiz Hermanos'],
            ['legajo' => 286, 'nombre' => 'SF Diversidad en servicios'],
            ['legajo' => 287, 'nombre' => 'Romanelli Oscar Alfredo'],
            ['legajo' => 288, 'nombre' => 'Estacion de servicio Demartino'],
            ['legajo' => 289, 'nombre' => 'ALFA 21'],
            ['legajo' => 290, 'nombre' => 'Arcangel Prevencion Digital SRL'],
        ]);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('proovedores');
    }
}
